LOVEFiLM=window.LOVEFiLM||{};LOVEFiLM.i18n=LOVEFiLM.i18n||(function(){var lang='en';var tags={};var locales={'_default':{lang:'_default',grammar:{chooseByNumber:function(n,choices){return'';},chooseByGender:function(gender,choices){return'';}},datetime:{unknown:''},number:{grouping:[],group_separator:'',decimal_separator:''},currency:{decimals:2,code:'',symbol:'',template:''}}};var tokenRegex=/\{((?:(link|gender):)?[a-z_][a-z0-9_]*)(?:\|((?:\{[^\}]+\}|[^\}]+))+)?\}/g;var iso8601Regex=/^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2}):(\d{2}))?$/;var mysqlDateTimeRegex=/^(\d{4})-(\d{2})-(\d{2})(?:\s(\d{2}):(\d{2}):(\d{2}))?$/;function augment(receiver,giver,replace){var prop;if(typeof giver==='object'){for(prop in giver){if(giver.hasOwnProperty(prop)&&(replace||!receiver.hasOwnProperty(prop))){receiver[prop]=giver[prop];}}}
return receiver;}
function htmlEscape(str){return str
.replace(/&/g,'&amp;')
.replace(/</g,'&lt;')
.replace(/>/g,'&gt;')
.replace(/"/g,'&quot;')
.replace(/'/g,'&#x27;');}
function evalLink(templateVar,value,formatArgs){var linkText=formatArgs[0];var linkTitle=formatArgs[1];var linkAttributes=typeof value==='object'?value:{href:value};linkAttributes.href=linkAttributes.href||'';if(linkTitle){linkAttributes.title=linkAttributes.title||linkTitle;}
linkText=linkAttributes.text||linkText;if(!linkText){linkText=linkAttributes.href
.replace(/^[a-z][\-+.a-z0-9]*:\/\//,'')
.replace(/[?#].*$/,'');}
delete linkAttributes.text;var parts=['<a'];var attribute;for(attribute in linkAttributes){if(linkAttributes.hasOwnProperty(attribute)){parts.push(' '
+htmlEscape(attribute)
+'="'
+htmlEscape(linkAttributes[attribute])
+'"');}}
parts.push('>'+htmlEscape(linkText)+'</a>');return parts.join('');}
function lformat(template,params){var parts=[];var tokenMatches;var locale=LOVEFiLM.i18n.getCurrentLocale();var previousLastIndex=0;while((tokenMatches=tokenRegex.exec(template))!==null){parts.push(template.substring(previousLastIndex,tokenMatches.index));var templateVar=tokenMatches[1];var qualifier=tokenMatches[2]||'';var formatArgs=tokenMatches[3]?tokenMatches[3].split('|'):[];var value=params[templateVar];switch(qualifier){case'':if(formatArgs.length===0){parts.push(value);}else{parts.push(locale.grammar.chooseByNumber(value,formatArgs)
.replace('#',value));}
break;case'gender':parts.push(locale.grammar.chooseByGender(value,formatArgs));break;case'link':parts.push(evalLink(templateVar,value,formatArgs));break;default:}
previousLastIndex=tokenRegex.lastIndex;}
parts.push(template.substr(previousLastIndex));return parts.join('');}
function zeroPad(num,digits){var zeroesToAdd=digits-num.toString().length;var zeroes=[];while(zeroesToAdd-zeroes.length>0){zeroes[zeroes.length]='0';}
return zeroes.join('')+num;}
function dateFormat(locale,date,type,options){if(date instanceof Date===false){return locale.datetime.unknown;}
type=type||'date';options=options||{};augment(options,{style:'compact',day:true,wday:false,secs:false});var template='';switch(type){case'time':template=locale.datetime['time'+(options.secs?'_secs':'')];break;case'date':template=locale.datetime['date_'+
(options.wday?'wday_':options.day?'day_':'')
+options.style];break;case'datetime':return locale.datetime.datetime.replace(/\{(date|time)\}/g,function(text,token){return dateFormat(locale,date,token,options);});break;default:template=locale.datetime.unknown;}
var parts={h:date.getHours(),h12:(date.getHours()-1)%12+1,hh:zeroPad(date.getHours(),2),hh12:zeroPad((date.getHours()-1)%12+1,2),mm:zeroPad(date.getMinutes(),2),ss:zeroPad(date.getSeconds(),2),ampm:date.getHours()>11?locale.datetime.pm:locale.datetime.am,wday:locale.datetime.wday_list[date.getDay()],wday_short:locale.datetime.wday_short_list[date.getDay()],day:zeroPad(date.getDate(),2),day_short:date.getDate(),day_ordinal:locale.datetime.day_ordinal_list[date.getDate()-1],month:zeroPad(date.getMonth()+1,2),month_name:locale.datetime.month_name_list[date.getMonth()],month_name_short:locale.datetime.month_name_short_list[date.getMonth()],year:date.getFullYear()};return template.replace(/\{([^}]+)\}/g,function(text,token){return token in parts?parts[token]:text;});}
return{setLanguage:function(newLang){lang=newLang;},getLanguage:function(){return lang;},addLocale:function(locale){locales[locale.lang]=locale;},getCurrentLocale:function(){var localeLang=lang;while(typeof locales[localeLang]==='undefined'){if(localeLang.indexOf('-')===-1){break;}
localeLang=localeLang.replace(/-[^\-]+$/,'');}
return locales[localeLang]||locales._default;},addTags:function(tagLang,tagsToAdd){var tag;for(tag in tagsToAdd){if(tagsToAdd.hasOwnProperty(tag)){if(typeof tags[tagLang]==='undefined'){tags[tagLang]={};}
tags[tagLang][tag]=tagsToAdd[tag];}}},clearTags:function(){tags={};},i18n:function(tag,params){params=params||{};var locale=LOVEFiLM.i18n.getCurrentLocale();var template=tags[locale.lang][tag];return lformat(template,params);},parseDate:function(date){var d=null;if(date instanceof Date){return date;}else if(typeof date==='string'){var matches=iso8601Regex.exec(date)||mysqlDateTimeRegex.exec(date);if(matches){d=new Date(matches[1],matches[2]-1,matches[3],matches[4]||0,matches[5]||0,matches[6]||0);}}
return d;},formatTime:function(date,seconds){return dateFormat(LOVEFiLM.i18n.getCurrentLocale(),LOVEFiLM.i18n.parseDate(date),'time',{secs:seconds});},formatDate:function(date,options){if(typeof options==='string'){options={style:options};}
return dateFormat(LOVEFiLM.i18n.getCurrentLocale(),LOVEFiLM.i18n.parseDate(date),'date',options);},formatDateTime:function(date,options){return dateFormat(LOVEFiLM.i18n.getCurrentLocale(),LOVEFiLM.i18n.parseDate(date),'datetime',options);},formatNumber:function(value,options){if(typeof value==='undefined'||value===null){return'';}
var numericValue=typeof value!=='number'?parseFloat(value.toString(),10):value;if(isNaN(numericValue)){return value;}
var locale=LOVEFiLM.i18n.getCurrentLocale();options=options||{};augment(options,{rounding:'nearest',decimals:0,ordinal:false});var formattedString=numericValue.toFixed(options.decimals);var odds=Math.abs(numericValue-parseFloat(formattedString,10));var rounding=options.rounding;if(rounding==='zero'){rounding=value<0?'up':'down';}
var roundingDelta=0;if(rounding==='up'&&odds>0){roundingDelta=0.5*Math.pow(10,0-options.decimals);}else if(rounding==='down'&&odds>0){roundingDelta=-0.5*Math.pow(10,0-options.decimals);}
formattedString=(numericValue+roundingDelta).toFixed(options.decimals);var parts=formattedString.split('.',2);var whole=parts[0];var frac=parts[1]||null;var sign='';if(whole.charAt(0)==='-'){sign='-';whole=whole.substr(1);}
var grouping=(locale.number&&locale.number.grouping&&locale.number.grouping.concat())||[];var groupSeparator=(locale.number&&locale.number.group_separator)||'';var decimalSeparator=(locale.number&&locale.number.decimal_separator)||'.';var width=3;var digits=whole.split('');var groups=[];while(digits.length>0){width=(grouping.length>0)?grouping.shift():width;if(width===-1||width>=digits.length){groups.push(digits.join(''));break;}else{groups.push(digits.splice(digits.length-width,width).join(''));}}
formattedString=sign
+groups.reverse().join(groupSeparator)
+(frac===null?'':decimalSeparator+frac);return formattedString;},formatCurrency:function(value,options){if(typeof value==='undefined'||value===null){return'';}
var numericValue=(typeof value!=='number')?parseFloat(value.toString(),10):value;if(isNaN(numericValue)){return value;}
var locale=LOVEFiLM.i18n.getCurrentLocale();options=options||{};augment(options,{template:null,rounding:null});var formattedValue=LOVEFiLM.i18n.formatNumber(numericValue,{decimals:locale.currency.decimals,rounding:options.rounding});var template=options.template||locale.currency.template||'';return template.replace(/\{(\w+)\}/g,function(match,token){return token==='value'?formattedValue:locale.currency[token];});},getCurrencyCode:function(){var locale=LOVEFiLM.i18n.getCurrentLocale();return locale.currency.code;},getCurrencySymbol:function(){var locale=LOVEFiLM.i18n.getCurrentLocale();return locale.currency.symbol;}};}());;LOVEFiLM.i18n.addLocale({lang:'en',name:'English',grammar:{chooseByNumber:function(n,choices){return choices[(n==1||choices.length<=1)?0:(n!=0||choices.length<=2)?1:2];},chooseByGender:function(gender,choices){return choices[(gender.indexOf('m')===0||choices.length<=1)?0:(gender.indexOf('f')!==0&&choices.length<=2)?0:(gender.indexOf('f')===0&&choices.length<=3)?1:2];}},datetime:{unknown:'unknown',time:'{hh}:{mm}',time_secs:'{hh}:{mm}:{ss}',ampm:['am','pm'],datetime:'{date}, {time}',date_compact:'{month}/{year}',date_day_compact:'{day}/{month}/{year}',date_wday_compact:'{wday_short} {day}/{month}/{year}',date_short:'{month_name_short} {year}',date_day_short:'{day} {month_name_short} {year}',date_wday_short:'{wday_short} {day} {month_name_short} {year}',date_medium:'{month_name} {year}',date_day_medium:'{day_short} {month_name} {year}',date_wday_medium:'{wday}, {day_short} {month_name} {year}',date_long:'{month_name} {year}',date_day_long:'{day_ordinal} {month_name} {year}',date_wday_long:'{wday}, {day_ordinal} {month_name} {year}',wday_list:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],wday_short_list:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],day_ordinal_list:['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st'],month_name_list:['January','February','March','April','May','June','July','August','September','October','November','December'],month_name_short_list:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']},number:{grouping:[3],group_separator:',',decimal_separator:'.'},currency:{decimals:2,code:'GBP',symbol:'\u00A3',template:'\u00A3{value}'}});;